import { defineTheme } from '../../types/theme';
import { modernSystemFont } from './shared';

/** High-contrast light preset with dark structure and vivid blue focus states. */
export const highContrastTheme = defineTheme({
  name: 'highContrast',
  extends: 'material',
  colorScheme: 'light',
  defaultRowSize: 40,
  tokens: {
    primary: '#003eaa',
    primaryTransparent: 'rgba(0, 62, 170, 0.92)',
    background: '#ffffff',
    foreground: '#000000',
    divider: '#374151',
    shadow: 'rgba(0, 0, 0, 0.35)',
    text: '#111827',
    border: '#374151',
    headerBg: '#111827',
    headerColor: '#ffffff',
    headerBorder: '#ffffff',
    headerFocusedBg: '#003eaa',
    headerHoverBg: '#1f2937',
    cellBorder: '#6b7280',
    focusedBg: '#d6e9ff',
    rowHover: '#e8f2ff',
    rowHeadersBg: '#e5e7eb',
    rowHeadersColor: '#000000',
    cellDisabledBg: '#d1d5db',
    filterPanelBg: '#ffffff',
    filterPanelBorder: '#111827',
    filterPanelShadow: 'rgba(0, 0, 0, 0.4)',
    filterPanelInputBg: '#ffffff',
    filterPanelDivider: '#4b5563',
    filterPanelSelectBorder: '#111827',
    filterPanelSelectBorderHover: '#003eaa',
    filterPanelReorderAccent: '#003eaa',
    filterPanelReorderColor: '#374151',
    filterPanelText: '#000000',
    filterPanelMutedText: '#374151',
    filterPanelFocusRing: '0 0 0 3px #ffbf00',
    filterPanelIcon: '#111827',
    filterPanelIconActive: '#003eaa',
    fontFamily: modernSystemFont,
    fontSize: '14px',
    headerHeight: '48px',
    headerFontSize: '13px',
    headerFontWeight: '700',
    headerTextTransform: 'none',
    headerTextAlign: 'left',
    cellTextAlign: 'left',
    headerPadding: '0 14px',
    cellPadding: '0 14px',
    selectionBorder: '#003eaa',
    selectionBg: 'rgba(0, 95, 204, 0.2)',
    autofillHandleBg: '#003eaa',
    autofillHandleBorder: '#ffffff',
    rangeHandleBg: 'rgba(0, 95, 204, 0.3)',
    temporaryRangeBorder: '#a61b1b',
    temporarySelectionBorder: '#5b21b6',
    headerResizeHover: '#ffbf00',
    buttonText: '#ffffff',
    buttonBg: '#003eaa',
    buttonSuccessBg: '#006b3c',
    buttonDangerBg: '#b91c1c',
    buttonOutlineBorder: '#111827',
    buttonOutlineText: '#111827',
  },
});
