import { defineTheme } from '../../types/theme';
import { modernSystemFont } from './shared';

/** High-contrast dark preset with luminous yellow and cyan interaction states. */
export const highContrastDarkTheme = defineTheme({
  name: 'highContrastDark',
  extends: 'darkMaterial',
  colorScheme: 'dark',
  defaultRowSize: 40,
  tokens: {
    primary: '#ffd400',
    primaryTransparent: 'rgba(255, 212, 0, 0.94)',
    background: '#050505',
    foreground: '#ffffff',
    divider: '#d1d5db',
    shadow: 'rgba(0, 0, 0, 0.8)',
    text: '#ffffff',
    border: '#bfc7d5',
    headerBg: '#171717',
    headerColor: '#ffffff',
    headerBorder: '#e5e7eb',
    headerFocusedBg: '#005f73',
    headerHoverBg: '#303030',
    cellBorder: '#737b87',
    cellVerticalBorder: '#737b87',
    focusedBg: '#182c3f',
    rowHover: '#202a33',
    rowHeadersBg: '#222222',
    rowHeadersColor: '#ffffff',
    cellDisabledBg: '#303030',
    filterPanelBg: '#0a0a0a',
    filterPanelBorder: '#ffffff',
    filterPanelShadow: 'rgba(0, 0, 0, 0.85)',
    filterPanelInputBg: '#171717',
    filterPanelDivider: '#d1d5db',
    filterPanelSelectBorder: '#e5e7eb',
    filterPanelSelectBorderHover: '#ffd400',
    filterPanelReorderAccent: '#00e5ff',
    filterPanelReorderColor: '#e5e7eb',
    filterPanelText: '#ffffff',
    filterPanelMutedText: '#d1d5db',
    filterPanelFocusRing: '0 0 0 3px #ffd400',
    filterPanelIcon: '#e5e7eb',
    filterPanelIconActive: '#ffd400',
    fontFamily: modernSystemFont,
    fontSize: '14px',
    headerHeight: '48px',
    headerFontSize: '13px',
    headerFontWeight: '700',
    headerTextTransform: 'none',
    headerTextAlign: 'left',
    cellTextAlign: 'left',
    headerPadding: '0 14px',
    cellPadding: '0 14px',
    selectionBorder: '#00e5ff',
    selectionBg: 'rgba(0, 229, 255, 0.2)',
    autofillHandleBg: '#ffd400',
    autofillHandleBorder: '#000000',
    rangeHandleBg: 'rgba(0, 229, 255, 0.32)',
    temporaryRangeBorder: '#ffd400',
    temporarySelectionBorder: '#ff7ad9',
    headerResizeHover: '#ffd400',
    buttonText: '#000000',
    buttonBg: '#ffd400',
    buttonSuccessBg: '#7cfc00',
    buttonDangerBg: '#ff8080',
    buttonOutlineBorder: '#ffffff',
    buttonOutlineText: '#ffffff',
  },
});
