import { defineTheme } from '../../types/theme';
import { modernSystemFont } from './shared';

/** Bright blue and slate preset for data-heavy daytime interfaces. */
export const oceanTheme = defineTheme({
  name: 'ocean',
  extends: 'material',
  colorScheme: 'light',
  defaultRowSize: 38,
  tokens: {
    primary: '#2563eb',
    primaryTransparent: 'rgba(37, 99, 235, 0.88)',
    background: '#f8fafc',
    foreground: '#0f172a',
    divider: '#cbd5e1',
    shadow: 'rgba(15, 23, 42, 0.16)',
    text: '#334155',
    border: '#d8e2ee',
    headerBg: '#eef4fb',
    headerColor: '#0f172a',
    headerBorder: '#d7e2ee',
    cellBorder: '#e5edf5',
    focusedBg: '#dbeafe',
    rowHover: '#eff6ff',
    rowHeadersBg: '#e7f0fa',
    rowHeadersColor: '#475569',
    cellDisabledBg: '#f1f5f9',
    filterPanelBg: '#ffffff',
    filterPanelBorder: '#dbe4ef',
    filterPanelShadow: 'rgba(15, 23, 42, 0.18)',
    filterPanelInputBg: '#f1f5f9',
    filterPanelDivider: '#e2e8f0',
    filterPanelSelectBorder: '#cbd5e1',
    filterPanelSelectBorderHover: '#2563eb',
    filterPanelReorderAccent: '#2563eb',
    filterPanelReorderColor: '#64748b',
    filterPanelText: '#334155',
    filterPanelMutedText: '#64748b',
    filterPanelFocusRing: '0 0 0 3px rgba(37, 99, 235, 0.2)',
    filterPanelIcon: '#64748b',
    filterPanelIconActive: '#2563eb',
    fontFamily: modernSystemFont,
    fontSize: '13px',
    headerHeight: '44px',
    headerFontSize: '12px',
    headerFontWeight: '650',
    headerTextTransform: 'none',
    headerTextAlign: 'left',
    cellTextAlign: 'left',
    headerPadding: '0 14px',
    cellPadding: '0 14px',
    selectionBorder: '#2563eb',
    selectionBg: 'rgba(37, 99, 235, 0.1)',
    autofillHandleBg: '#2563eb',
    autofillHandleBorder: '#ffffff',
    rangeHandleBg: 'rgba(37, 99, 235, 0.22)',
    temporaryRangeBorder: '#f97316',
    temporarySelectionBorder: '#64748b',
    headerResizeHover: '#3b82f6',
    buttonText: '#ffffff',
    buttonBg: '#2563eb',
    buttonSuccessBg: '#059669',
    buttonDangerBg: '#dc2626',
    buttonOutlineBorder: '#cbd5e1',
    buttonOutlineText: '#334155',
  },
});
